# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozivnica',
            name='korisnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozvani', to='restoran.Korisnik'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='korisnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korisnik', to='restoran.Korisnik'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='zvanice',
            field=models.ManyToManyField(related_name='zvanice', to='restoran.Korisnik'),
        ),
    ]
