# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0005_restoran_menadzer'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='picture',
            field=models.ImageField(blank=True, default=b'pic_folder/no-img.jpg', null=True, upload_to=b'pic_folder'),
        ),
        migrations.AlterField(
            model_name='pozivnica',
            name='stanje',
            field=models.CharField(choices=[(b'A', b'Accepted'), (b'D', b'Decline'), (b'P', b'Pending')], default=b'P', max_length=1),
        ),
    ]
