# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0006_auto_20151219_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField()),
                ('ocenjivac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoran.Korisnik')),
            ],
        ),
        migrations.AddField(
            model_name='restoran',
            name='ocene',
            field=models.ManyToManyField(to='restoran.Ocena'),
        ),
    ]
