# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0007_auto_20151222_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='poseta',
            name='ocenjen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='zvanice',
            field=models.ManyToManyField(blank=True, related_name='zvanice', to='restoran.Korisnik'),
        ),
    ]
