# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0009_remove_poseta_ocenjen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozivnica',
            name='ocena',
            field=models.IntegerField(default=0),
        ),
    ]
