# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0011_auto_20151224_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restoran',
            name='ocene',
            field=models.ManyToManyField(blank=True, to='restoran.Ocena'),
        ),
    ]
