# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0012_auto_20151225_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervacija',
            name='datum',
            field=models.DateTimeField(unique=True, verbose_name=b'date published'),
        ),
    ]
