# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0014_rezervacija_stolovi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervacija',
            name='stolovi',
            field=models.ManyToManyField(blank=True, related_name='stolovi', to='restoran.Sto'),
        ),
    ]
